### ISSUE TITLE
Removing batch effects

### ISSUE THREAD

**Issue by kfuku52** [aayushraman/DASC#1]
Hi, Thank you for developing the excellent tool. I have read through the DASC user guide but couldn't find out how we can remove the detected batch effects from the original data matrix. Could you tell me if there is another tutorial explaining it?

**Comment by aayushraman** [comment]
DASC is used for the detection of batch effects, and not for correction. However, you may use detected batches as the covariates in your linear or glm model (in DESeq2, edgeR or limma) for differential expression analysis.

**Comment by kfuku52** [comment]
Thank you for clarifying. I will look into the GLM-based packages to figure out if they fit my purpose.
