### ISSUE TITLE
manual and examples

### ISSUE THREAD

**Issue by poflawless** [aayushraman/DASC#2]
Thanks for your work of DASC, while the url for DASC in bioconductor hasn't existed any longer and the manual for users to instruct us do analysis stepwisly couldn't be found.
In my work the batch labels were not known, so the examples of Topotecan RNAseq dataset will help me a lot. Could you please add that to the manual or guide?
What's more, the  982869874@qq.com can't be reached, please give me some advices

**Comment by aayushraman** [comment]
I apologize for the inconvenience. Here is the link for our Bioconductor package: https://bioconductor.org/packages/3.6/bioc/html/DASC.html. Here is the manual: https://bioconductor.org/packages/3.6/bioc/vignettes/DASC/inst/doc/DASC_html.html

Here are the details about Topotecan Dataset:
![topdataset](https://user-images.githubusercontent.com/4062603/40316634-8f3ccf7a-5ce4-11e8-9c35-53ffdc963295.jpg) . I parsed the information from fastq files and STAR alignment results.

Also, please run DASC on R version 3.2 or less. DASC uses R NMF package, and we supply our cost function to nmf function. For some unknown reason, it gives the error when we use R version > 3.2. We are currently working on it to make it run on any R version. We apologize for the inconvenience.
